import {PurchaseQuotation} from './purchase.model';

export const PURCHASEQUOTATION: PurchaseQuotation[] = [
    {
        id: 1,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 2,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 3,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 4,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 5,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 6,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    }
];

