import {SalesQuotation} from './sales.model';

export const SALESQUOTATION: SalesQuotation[] = [
    {
        id: 1,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 2,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 3,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 4,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 5,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 6,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 7,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 8,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 9,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 10,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 11,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 12,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 13,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    },
    {
        id: 14,
        quotation_no: 'SALQ202311-000005',
        quotation_date: '07/11/2023',
        customer_name: 'PCOMMS',
        quoted_by: 'David',
        reg_no: 'ABC1234D',
        make: 'SUBARU',
        model: '2020 FORESTER MILD XXX',
        status: 'OPEN',
    }
];

